name: 'Build'

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch: # Allow you to run this workflow manually from the Action tab
  
env:
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: AnyCPU
  CSPROJ_PATH: HelloDeploy\HelloDeploy.csproj
  HELLO_ARTIFACT_NAME: HelloDeploy
  LOCAL_DIR: ${{ github.workspace }}/
  SERVER_DIR: /site/wwwroot/hello-deploy/
  VERSION: '1.0.0.10'
      
jobs:

  build-and-publish:
    runs-on: windows-latest 
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
                    
    - name: 'Setup MSBuild'
      uses: microsoft/setup-msbuild@v1.3.1

    - name: 'Setup Nuget'
      uses: NuGet/setup-nuget@v1.2.0

    - name: 'Nuget Restore Packages'
      run: nuget restore "HelloDeploy.sln"

    - name: "Build"
      run: msbuild ${{ env.CSPROJ_PATH }} /t:build /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:Platform=${{ env.BUILD_PLATFORM }}

    - name: "Publish"
      run: |
        msbuild ${{ env.CSPROJ_PATH }} /t:publish /p:Configuration="${{ env.BUILD_CONFIGURATION }}" /p:Platform="${{ env.BUILD_PLATFORM }}" /p:ApplicationVersion="${{ env.VERSION }}" /p:MinimumRequiredVersion="${{ env.VERSION }}" /p:VersionAssembly="${{ env.VERSION }}"
    
    - name: "Upload Artifact"
      uses: actions/upload-artifact@v4.3.0
      with:
        name: ${{ env.HELLO_ARTIFACT_NAME }}
        path: ${{ env.LOCAL_DIR }}

  deploy-by-ftp:
    name: Deploy by FTP
    runs-on: windows-latest
    needs: build-and-publish
    steps:
    - name: Get latest code
      uses: actions/checkout@v4
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_HOSTNAME }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWD }}
        server-dir: ${{ env.SERVER_DIR }}
        local-dir: ${{ env.LOCAL_DIR }}
        protocol: ftps
